### ISSUE TITLE
Currently No Way to Alter or Shorten the Fleet Name

### ISSUE THREAD

**Issue by jacobmammoliti** [GoogleCloudPlatform/gke-fleet-management#11]
There does not seem to be a way to alter or shorten the Fleet name which causes issues with character lengths and RFC 1035. Given this ApplicationSet:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
  - plugin:
      configMapRef:
        name: argocd-fleet-sync
      input:
        parameters:
          fleetProjectNumber: "$FLEET_PROJECT_NUMBER"
          scopeID: "$TEAM_ID"
      requeueAfterSeconds: 10
  template:
    metadata:
      name: '{{ name }}-nginx'
    spec:
      project: default
      source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.11.3
      destination:
        server: '{{ server }}'
        namespace: ingress-nginx
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

The only way to have unique ArgoCD Application name's is via the cluster's full fleet name ie. `<gke_cluster_name>.global.<gcp_project_number>`. This fails in cases where a Helm Chart uses the name in its template for Kubernetes objects as shown in this example below:

```
one or more objects failed to apply, reason: Service "non-production-application.global.772391010134-nginx-ingress-ng" is invalid: metadata.name: Invalid value: "non-production-application.global.772391010134-nginx-ingress-ng": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'),Service "non-production-application.global.772391010134-nginx-ingress-ng-admission" is invalid: [metadata.name: Invalid value: "non-production-application.global.772391010134-nginx-ingress-ng-admission": must be no more than 63 characters, metadata.name: Invalid value: "non-production-application.global.772391010134-nginx-ingress-ng-admission": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]
```

This also proves to be challenging if the GKE cluster has a long name given the 63 character limit on some objects.
